title: Cris y Alex se casan!
logo: /assets/img/citra.png
description: Nos hace mucha ilusión invitaros a nuestra boda el próximo 6 de julio en la iglesia Santa Maria de Caná y a celebrarlo en la finca Villasolita. Aquí podreis encontrar todos los detalles sobre nuestra boda.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
baseurl: "alexycrissecasan.com"
